---
# tasks file for desktop
- name: install i3 window manager
  apt:
    name: ['i3', 'xinit']

- name: set i3 autostart in /etc/profile
  lineinfile:
    path: /etc/profile
    line: startx /usr/bin/i3

- name: install volume control
  apt:
    name: ['alsa-utils']

- name: install snap
  apt:
    name: ['snapd']
  tags:
    - snap
