---
# tasks file for apps
- name: Install terminal emulator
  apt:
    name: xterm

- name: Install brave browser repo key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
  tags:
    - brave-browser

- name: Install brave browser repo
  apt_repository:
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com bionic main
    filename: brave
    state: absent
  tags:
    - brave-browser

- name: Install brave browser
  apt:
    name: brave-browser
    update_cache: yes
    state: absent
  tags:
    - brave-browser
