---
# tasks file for apps
- name: Install terminal emulator
  apt:
    name: xterm

- name: Install Chrome Web-browser
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    update_cache: yes
  tags:
    - chrome-browser
